const getNationalities = () => {
  return [
    'Algerian',
    'Argentinian',
    'Australian',
    'Austrian',
    'Bangladeshi',
    'Belgian',
    'Bolivian',
    'Batswana',
    'Brazilian',
    'Bulgarian',
    'Cambodian',
    'Cambodian',
    'Canadian',
    'Chilean',
    'Colombian',
    'Costa',
    'Rican',
    'Croatian',
    'Czech',
    'Danish',
    'Dominican',
    'Ecuadorian',
    'Egyptian',
    'Salvadorian',
    'English',
    'Estonian',
    'Fijian',
    'Finnish',
    'French',
    'German',
    'Ghanaian',
    'Greek',
    'Guatemalan',
    'Haitian',
    'Honduran',
    'Hungarian',
    'Icelandic',
    'Indian',
    'Indonesian',
    'Irish',
    'Israeli',
    'Italian',
    'Jamaican',
    'Japanese',
    'Jordanian',
    'Kenyan',
    'Kuwaiti',
    'Lao',
    'Latvian',
    'Lithuanian',
    'Malagasy',
    'Malaysian',
    'Malian',
    'Maltese',
    'Mexican',
    'Mongolian',
    'Moroccan',
    'Mozambican',
    'Namibian',
    'Nepalese',
    'Dutch',
    'New Zealand',
    'Nicaraguan',
    'Nigerian',
    'Norwegian',
    'Panamanian',
    'Paraguayan',
    'Peruvian',
    'Philippine',
    'Polish',
    'Portuguese',
    'Romanian',
    'Saudi',
    'Scottish',
    'Senegalese',
    'Serbian',
    'Singaporean',
    'Slovak',
    'South African',
    'Korean',
    'Spanish',
    'Swedish',
    'Swiss',
    'Taiwanese',
    'Tajikistani',
    'Thai',
    'Tongan',
    'Tunisian',
    'Turkish',
    'Ukrainian',
    'Emirati',
    'British',
    'American',
    'Uruguayan',
    'Vietnamese',
    'Welsh'
  ];
};

const getBlackList = () => {
  return [
    'Afghanistan',
    'Albania',
    'Belarus',
    'Bosnia and Herzegovina',
    'Burundi',
    'Central African',
    'Republic China',
    'Core d’Ivoire',
    'Cuba',
    'Democratic Republic of the Congo',
    'Eritrea',
    'Ethiopia',
    'Guinea',
    'Guinea-Bissau',
    'Haiti',
    'Iran',
    'Iraq',
    'Kyrgyzstan',
    'Lebanon',
    'Liberia',
    'Libya',
    'Myanmar',
    'North Korea',
    'North Macedonia',
    'Palestine',
    'Rwanda',
    'Russia',
    'Somalia',
    'South Sudan',
    'Sri Lanka',
    'Sudan',
    'Syria',
    'Trinidad and Tobago',
    'Tunisia',
    'Uganda',
    'Venezuela',
    'Yemen',
    'Zimbabwe'
  ];
};

export { getNationalities, getBlackList };
